services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "80:8501"
    restart: unless-stopped

    environment:
      RETRIEVAL_HOST: retrieval
      RETRIEVAL_PORT: 8080